routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::resource('posts', 'Site\\PostController')->except('show')->middleware('auth');
Route::get('/posts/{id}/{slug}', 'Site\\PostController@show')->name('posts.show');
Route::post('/post/like', 'Site\\LikeController@postLike')->name('like.post')->middleware('auth');
/**
 * Admin
 */
Route::group(['prefix'=>'admin','namespace'=>'Admin','middleware' => ['is_admin','auth'],'as'=>'admin.'], function () {
    Route::get('/', 'AdminController@index')->name('home');
    Route::resource('posts', 'PostController')->except('show')->middleware('auth');
    Route::resource('users', 'UserController')->except('show')->middleware('auth');
    Route::post('/changeUserPassword', 'ChangePasswordController@changeUserPassword')->name('changePassword.changeUserPassword')->middleware('auth');
    Route::get('/edit', 'AdminController@edit')->name('edit');
    Route::get('change-password', 'ChangePasswordController@createAdminPassword')->name('changePassword.createAdminPassword');
    Route::post('change-password', 'ChangePasswordController@storeAdminPassword')->name('changePassword.storeAdminPassword');
});

app/User.php
<?php

namespace App;

use App\Models\Role;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
    const DEFAULT_TYPE = 2;
    const ADMIN_TYPE = 1;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Check Is Admin
     * @return bool
     */
    public function isAdmin()
    {
        return $this->role_id === self::ADMIN_TYPE;
    }

    /**
     * User Role
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function role()
    {
        return $this->belongsTo(Role::class);
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreAdminUser;
use App\Models\Role;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Gate;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::where('role_id', '=', User::DEFAULT_TYPE)->get();
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::get();
        return view('admin.users.create',compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAdminUser $request)
    {
        $request['password'] = Hash::make($request->password);
        User::create($request->all());
        return redirect()->route('admin.users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $roles = Role::get();
        Gate::authorize('edit', $user);
        return view('admin.users.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $input = $request->all();
            $this->validate($request,
                [
                    'name' => 'required:string|max:191',
                    'email' => 'required:string|max:191',
                ]);
            if ($user->email != $request->get('email')) {
                $this->validate($request,
                    [
                        'email' => 'required|unique:users',
                    ]);
            }
            $user->fill($input)->save();
            Session::flash('flash_message', 'Your data successfully changed!');
            return redirect()->route('admin.users.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (request()->ajax()) {
            User::destroy($id);
            return response()->json(['success' => true, 'id' => $id]);

        }
        return response()->json(['success' => false]);
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.master')
@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">User create</h1>
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <div class="container">
                    <div class="col-md-8 offset-md-2">
                        @include('admin.users.form',array('method'=>'POST','action'=> route('admin.users.store')))
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.master')
@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">User edit</h1>

    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <div class="container">
                    <div class="col-md-8 offset-md-2">
                        @include('admin.users.form',array('method'=>'POST','update'=>true,'action'=> route('admin.users.update',array('user'=>$user['id']))))
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/form.blade.php
<form action="{{$action}}" method="{{$method}}">
    @csrf
    @if(isset($update))
        @method('PUT')
    @endif
    <div class="form-group">
        <label for="title">Name</label>
        <input
                type="text"
                name="name"
                class="form-control title-post {{$errors->has('name')?'text-danger is-invalid':(old('name')?'is-valid':'')}}"
                id="name"
                value="{{isset($user)?old('name',$user['name']):old('name') }}"
                placeholder="Name">
        @if($errors->has('name'))
            <small class="text-danger error">
                {{ $errors->first('name') }}
            </small>
        @endif
    </div>
    <div class="form-group">
        <label for="title">Email</label>
        <input
                type="email"
                name="email"
                class="form-control title-post {{$errors->has('email')?'text-danger is-invalid':(old('email')?'is-valid':'')}}"
                id="email"
                value="{{isset($user)?old('email',$user['email']):old('email') }}"
                placeholder="Email">
        @if($errors->has('email'))
            <small class="text-danger error">
                {{ $errors->first('email') }}
            </small>
        @endif
    </div>
    <div class="form-group">
        <label for="role">Role</label>
        <select class="form-control form-control-lg {{$errors->has('role_id')?'text-danger is-invalid':(old('role_id')?'is-valid':'')}}"
                id="role" name="role_id">
            @if(!isset($user))
                <option value="">Select role user</option>
            @endif
            @foreach($roles as $role)
                <option value="{{$role['id']}}" {{ isset($user) && $role['id'] === $user['role_id'] ? 'selected':'' }}>{{$role['role']}}</option>
            @endforeach
        </select>
        @if($errors->has('role'))
            <small class="text-danger error">
                {{ $errors->first('role') }}
            </small>
        @endif
    </div>
    @if(!isset($update))
        <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" name="password" class="form-control" id="password" placeholder="Password">
            @if($errors->has('password'))
                <small class="text-danger error">
                    {{ $errors->first('password') }}
                </small>
            @endif
        </div>
    @endif

    <div class="form-group text-center">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

resources/views/admin/users/index.blade.php
@extends('admin.layouts.master')
@section('content')


    <!-- Page Heading -->
    <div class="page-heading clearfix mb-2">
        <h1 class="h3 mb-2 text-gray-800 fa-pull-left">Users</h1>
        <a href="{{route('admin.users.create')}}" class="btn btn-success fa-pull-right">Create</a>
    </div>


    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Role</th>
                        <th>Email</th>
                        <th>Edit</th>
                        <th>Delete</th>
                        <th>Change Password</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Role</th>
                        <th>Email</th>
                        <th>Edit</th>
                        <th>Delete</th>
                        <th>Change Password</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    @foreach($users as $user)
                        <tr id="delete-item-{{$user['id']}}">
                            <td>{{$user['id']}}</td>
                            <td>{{$user->name}}</td>
                            <td>{{$user->role->role}}</td>
                            <td style="max-width:600px">{{$user['email']}}</td>
                            <td >
                                <a href="{{route('admin.users.edit',array('user'=>$user['id']))}}" class="btn btn-warning btn-icon-split">
                                    <span class="text">Edit</span>
                                </a>
                            </td>
                            <td>
                                <a
                                        href="#deleteModal"
                                        data-toggle="modal"
                                        data-url="{{route('admin.users.destroy',array('user'=>$user['id']))}}"
                                        data-id="{{$user['id']}}"
                                        class="btn btn-danger btn-icon-split delete-item">
                                    <span class="text">Delete</span>
                                </a>
                            </td>
                            <td>
                                <a
                                        href="#changePassword"
                                        data-url="{{route('admin.changePassword.changeUserPassword')}}"
                                        data-id="{{$user['id']}}"
                                        class="btn btn-dark btn-icon-split change-password">
                                    <span class="text">Change</span>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    @include('modals.delete')
    @include('modals.changePassword')
    <input type="hidden" id="url" value="">
    <input type="hidden" id="item-id-val" value="">
@endsection
@section('script')
    <script src="{{asset('admin/js/user-index.js')}}"></script>
@endsection