routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::resource('posts', 'Site\\PostController')->except('show')->middleware('auth');
Route::get('/posts/{id}/{slug}', 'Site\\PostController@show')->name('posts.show');
Route::post('/post/like', 'Site\\LikeController@postLike')->name('like.post')->middleware('auth');
/**
 * Admin
 */
Route::group(['prefix'=>'admin','namespace'=>'Admin','middleware' => ['is_admin','auth'],'as'=>'admin.'], function () {
    Route::get('/', 'AdminController@index')->name('home');
    Route::resource('posts', 'PostController')->except('show')->middleware('auth');
    Route::resource('users', 'UserController')->except('show')->middleware('auth');
    Route::post('/changeUserPassword', 'ChangePasswordController@changeUserPassword')->name('changePassword.changeUserPassword')->middleware('auth');
    Route::get('/edit', 'AdminController@edit')->name('edit');
    Route::get('change-password', 'ChangePasswordController@createAdminPassword')->name('changePassword.createAdminPassword');
    Route::post('change-password', 'ChangePasswordController@storeAdminPassword')->name('changePassword.storeAdminPassword');
});

app/Models/Post.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    /**
     * @var array
     */
    protected $fillable =
        [
            'user_id',
            'title',
            'description',
            'slug'
        ];

    /**
     * table likes
     * Get the likes for the blog post.
     */
    public function likes()
    {
        return $this->hasMany(Like::class)->where('value','=',1);
    }

    /**
     * table likes
     * Get the dislikes for the blog post.
     */
    public function dislikes()
    {
        return $this->hasMany(Like::class)->where('value','=',0);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\RequestPost;
use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::get();
        return view('admin.posts.index',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.posts.crate');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RequestPost $request)
    {
        Post::create($request->all());
        return redirect()->route('admin.posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        return view('admin.posts.edit',compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RequestPost $request, $id)
    {
        $post = Post::find($id);
        $post->update($request->all());
        return redirect()->route('admin.posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(request()->ajax())
        {
            $post = Post::find($id);
            $post->delete();
            return response()->json(['success' => true,'id'=>$id]);

        }
    }
}

app/Http/Controllers/Site/PostController.php
<?php

namespace App\Http\Controllers\Site;

use App\Http\Controllers\Controller;
use App\Http\Requests\RequestPost;
use App\Http\Requests\StorePost;
use App\Models\Like;
use App\Models\Post;
use Illuminate\Auth\Access\Response;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RequestPost $request)
    {

        $post =  Post::create($request->all());
        return redirect()->route('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id,$slug)
    {
        $post = Post::find($id);
        return view('posts.show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        Gate::authorize('edit', $post);
        return view('posts.edit',compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RequestPost $request, $id)
    {
        $post = Post::find($id);
        Gate::authorize('update', $post);
        $post->update($request->all());
        return redirect()->route('home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(request()->ajax())
        {
            $post = Post::find($id);
            Gate::authorize('destroy', $post);
            //Post::destroy($id);
            $post->delete();
            return response()->json(['success' => true,'id'=>$id]);

        }
        return response()->json(['success' => false]);
    }


}

resources/views/admin/posts/crate.blade.php
@extends('admin.layouts.master')
@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Post create</h1>
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <div class="container">
                    <div class="col-md-8 offset-md-2">
                        @include('admin.posts.form',array('method'=>'POST','action'=> route('admin.posts.store')))
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/posts/edit.blade.php
@extends('admin.layouts.master')
@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Post edit</h1>
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <div class="container">
                    <div class="col-md-8 offset-md-2">
                        @include('admin.posts.form',array('method'=>'POST','update'=>true,'action'=> route('admin.posts.update',array('post'=>$post['id']))))
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/posts/form.blade.php
<form action="{{$action}}" method="{{$method}}">
    @csrf
    @if(isset($update))
        @method('PUT')
        <input type="hidden" name="role_id" value="{{$post['user_id']}}">
    @endif
    <div class="form-group">
        <label for="title">Title</label>
        <input
                type="text"
                name="title"
                class="form-control title-post {{$errors->has('title')?'text-danger is-invalid':(old('title')?'is-valid':'')}}"
                id="title"
                value="{{isset($post)?old('title',$post['title']):old('title') }}"
                placeholder="Title">
        @if($errors->has('title'))
            <small class="text-danger error">
                {{ $errors->first('title') }}
            </small>
        @endif
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <textarea
                class="form-control description-post  {{$errors->has('description')?'text-danger is-invalid':(old('description')?'is-valid':'')}}"
                name="description"
                id="description"
                rows="3">{{isset($post)?old('description',$post['description']):old('description') }}</textarea>
        @if($errors->has('description'))
            <small class="text-danger error">
                {{ $errors->first('description') }}
            </small>
        @endif
    </div>
    <div class="form-group text-center">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

resources/views/admin/posts/index.blade.php
@extends('admin.layouts.master')
@section('content')


    <!-- Page Heading -->
    <div class="page-heading clearfix mb-2">
        <h1 class="h3 mb-2 text-gray-800 fa-pull-left">Posts</h1>
        <a href="{{route('admin.posts.create')}}" class="btn btn-success fa-pull-right">Create</a>
    </div>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>User name</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>#</th>
                        <th>User name</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    @foreach($posts as $post)
                        <tr id="delete-item-{{$post['id']}}">
                            <td>{{$post['id']}}</td>
                            <td>{{$post->user->name}}</td>
                            <td>{{$post['title']}}</td>
                            <td style="max-width:600px">{{$post['description']}}</td>
                            <td>
                                <a href="{{route('admin.posts.edit',array('post'=>$post['id']))}}" class="btn btn-warning btn-icon-split dtc_edit">
                                    <span class="text">Edit</span>
                                </a>
                            </td>
                            <td>
                                <a
                                        href="#deleteModal"
                                        data-toggle="modal"
                                        class="btn btn-danger btn-icon-split delete-item"
                                        data-url="{{route('admin.posts.destroy',array('post'=>$post['id']))}}"
                                        data-id="{{$post['id']}}">
                                    <span class="text">Delete</span>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    @include('modals.delete')
    <input type="hidden" id="url" value="">
    <input type="hidden" id="item-id-val" value="">
@endsection
@section('script')
    <script src="{{asset('admin/js/admin-post.js')}}"></script>
@endsection